### ISSUE TITLE
General questions

### ISSUE THREAD

**Issue by ghost** [clojure-emacs/example-config#1]
Thanks again for doing this. Here is my first round of questions:

1) Why is cfg-clojuremode.el totally empty? What is this file for, what might eventually be in it?

2) I gather from the elpa/ directory that all packages used in this repo are from elpa only, and that emacs will not need to download/install them because they are already included here, is that right? 

3) Going forward, when there are upgrades to packages like cider or refactor, would it be better for a user to upgrade them directly through elpa, or via pulls from this repository, or would it make a difference -- in that, any upgrades via this repo would be identical to upgrades via elpa through emacs directly?

4) dash.el, queue.el, s.el -- are these primarily for elisp work? Sometimes it is not clear which of these files is clojure-specific and which is not. Perhaps an explanation in the file about why it is included, i.e. is it because some of the other files depend on these elisp functions? Since we are seeking a minimal setup that is clojure-specific, anything that is not critical for all the clojure tools should offer an explanation about its inclusion, or should be omitted. 

I'll have much more to report after I play around with this config for awhile.

**Comment by benedekfazekas** [comment]
1. I added a line of config there but @bbatsov pointed out that it is redundant. I still left the file there expecting some config to show up eventually. (I quickly checked [clojure-mode](https://github.com/clojure-emacs/clojure-mode) readme: and it seems there is not much to config unless you want different indentation for threading macros or such -- so in fact i might remove the that config file all together)
2. correct
3. depends which repo you prefer. in the example config as stated in the readme melpa-stable is used. well, mostly. I cheated a bit to be able to pull in latest for `clj-refactor` because I am one of its developers ;). going forward I suppose the maintainer of this example config should upgrade packages from stable and push the upgrades for this project's users for convenience. I already do something like this for my teammates where I work btw.
4. exactly as you said: these are elisp libraries which are dependencies of the listed packages. so they are essential: without them cider or clj-refactor won't work as their elisp code will fail without its dependencies. I did not want to overcomplicate the readme or the comments with details about these, although if you are interested in elisp a bit I deffo recommend to check out both dash.el and s.el. specially dash.el makes coding in elisp very similar to clojure coding.

hope this helps

**Comment by expez** [comment]
Why is the `elpa` directory checked in?  This is especially redundant when packages are pulled from `melpa-stable`.

Shouldn't we just provide the config and let the user decide whether whey want to ride `master` or run on `stable`?

**Comment by expez** [comment]
How should we deal with options?  Right now there's both `hl-sexp` and `show-paren-mode` enabled in the config.  I was thinking about adding a config for smartparens, which I've been trying out lately as an alternative to paredit, and that too has a minor mode which lets you highlight open/close pairs (or entire sexps).

As this is a starting point, perhaps we shouldn't provide tons of options at all and just pick one of the alternatives but link to other interesting packages in the readme?  I feel like maintaining a working config for emacs itself is better done by projects like [prelude](https://github.com/bbatsov/prelude) and we should narrow our focus to the clj specific tools?  Infact, perhaps our config should be meant to work with projects like [prelude](https://github.com/bbatsov/prelude) or [emacs-live](https://github.com/overtone/emacs-live)?

**Comment by benedekfazekas** [comment]
elpa is just a directory I suppose in this context.

master or stable: I guess the main point here to provide something which can be used out of the box for newcomers. the less they need to do extra configuration the better.

options: i guess we need to find a good balance/compromise: keep it clojure development focused **and** simple. won't be necessarily easy. I would
- try to make a decision which way to go
- branch or fork the repo (the more we branch/fork the more we need to invest into maintenance tho)

**Comment by arrdem** [comment]
I would argue strongly against this project being a framework like emacs-live or prelude. I think that @technomancy's comments on his old emacs starter kit and why he chose to abandon it apply here. What we need is not yet another framework, it's a set of small pluggable, copyable options so that users can see examples of how to configure a wide spectrum of tools applicable to Clojure development. To that end I think it's reasonable to show all of `show-smartparens-mode`, `show-paren-mode`, `hl-sexp` and soforth. If we can provide commentary on choosing one so much the better.

**Comment by benedekfazekas** [comment]
we can do more with

> ;; uncomment the next line if you want to use smartparens

style. but we need to keep it functional and few steps to set up I think.

**Comment by arrdem** [comment]
The way I structure my personal dotfiles is as follows:

`~/.emacs` sorts ~/.emacs.d/conf, loads them sequentially

`~/.emacs.d/conf/XX-MODE.el` configures a single mode or tool. Ex. `~/.emacs.d/conf/0-packages.el` initializes the package system and has a list of all the stuff I want to keep directly installed. This means I can blow away `~/.emacs.d/elpa` with impunity.

`~/.emacs.d/conf/$HOSTNAME/XX-MODE.el` has more configuration files specific to a given system since I have three machines some of which want minor tweaks.

I mention this structure, because it allows me to have a `20-smartparens.el`, a `20-cider.el` and then in `90-clojure.el` just say that I'm going to use cider and smartparens with with clojure-mode. This sort of single pluggable file structure I think is something we could follow nicely.

Alternatively having short logically broken configuration blocks suitable for copying to ones own configuration would work great too.

I think that trying to say "Just clone this and use it" will bring us no end of pain in the long run.

**Comment by benedekfazekas** [comment]
this sounds smart but does not sound simple. I don't really get what you mean by

> I think that trying to say "Just clone this and use it" will bring us no end of pain in the long run.

where is the pain in the long run with the clone it and use it approach?

in other words such a project as this does not save any newcomer the work to really understand the development environment (at some point) but it does lower the entry barrier.

**Comment by ghost** [comment]
If we adhere to the spirit of the original goal, then this is definitely a repo that someone should be able to clone and use directly. That is the whole idea.

I very much agree that we don't want something like emacs-live, that is not the goal. The idea here is that someone can use this immediately, and if they want to try something else, like smart-parens instead of paredit, then a simple comment-uncomment in the init.el or wherever seems simple and very useful to me. Ultimately, any emacs user will _eventually_ need to learn how to configure stuff on their own when they get to the point of wanting a more customized experience, but it needs to be easy for them to see how it is done in the first place, without a lot of "framework boilerplate" in there to complicate the ideas.

**Comment by benedekfazekas** [comment]
@arrdem thinking about your comment/point perhaps a good approach would be to maintain a dedicated readme here for people looking for extending their clojure focused emacs config. in this readme we could link and/or describe nice emacs hacks personal configs with an intro. by intro I mean something like your previous comment.

there are loads of resources on this on the internets but perhaps a dedicated, clojure focused document would have some value. thoughts?

**Comment by ghost** [comment]
The first thing I will be adding to my own config is rainbow parens, which I also consider quite important/useful for clojure editing.

**Comment by ghost** [comment]
I'm a bit confused in these lines:

(require 'package)
(add-to-list 'package-archives
             '("melpa-stable" . "http://stable.melpa.org/packages/") t)
(setq package-user-dir (concat user-emacs-directory "elpa"))

Does this mean that emacs will attempt to automatically update all these tools from melpa, but that for the intial installation they are all running from elpa? I know you said elpa was just an ordinary directory in this regard, but then does that mean it becomes the place where melpa packages go? aren't melpa and elpa two different things?

**Comment by bbatsov** [comment]
My thoughts are that we shouldn't overdo this. If were up to me the config would have been a single init.el file and the required packages would have been auto-downloaded. The more complex this is, the more confusing it will be for beginners (or at least I think so).

**Comment by ghost** [comment]
@bbatsov i like that idea, I think it would be good for the packages to download directly so that questions like the one I just asked don't confuse anyone else also. The goal here is not just to create a config that works for clojure editing, but that also nudges people in the direction of understanding how emacs works.

**Comment by ghost** [comment]
and.. if the packages are always kept up to date on melpa or elpa or wherever, then maintainers of the libraries would not need to constantly update this example-config with new library files since users would get the latest updates whenever they run this config for the first time... if I understand correctly how emacs works.

**Comment by benedekfazekas** [comment]
hm... if we go the autodownload predefined set of packages way
- we need to use melpa-stable for reliability (or maintain our own small repo?!) -- so I can't cheat and put clj-refactor latest in the bundle :(
- if we auto download stuff even from stable we need some means of autotest that the bundle is functional in other words autodownload means less control over what versions are in the bundle
- we add one more quite error prone step of setup (downloading packages)

single init.el: that is deffo an option. those cfg-\* files could be easily merged into init.el

**Comment by ghost** [comment]
well that's valid; is your latest clj-refactor not going upon the package managers any time soon?

and you are correct that sometimes the auto-download stuff doesn't quite work out as intended. for me, i'd be satisfied if my question a couple up was addressed, because i know i won't be the only one to have it. why is everything pulled from melpa when the directory in the config is elpa? what does that mean? also, having the melpa URL there means what exactly, if the user is not actually downloading the packages?

**Comment by benedekfazekas** [comment]
well, let's see:
1. clj-refactor is both on melpa and melpa stable but melpa stable has the last released version (0.13.0) while melpa has latest from master, aka a snapshot in other terms of versioning. I only added released versions to this bundle except clj-refactor.
2. if you look at this code snippet
   
   ``` elisp
   (require 'package)
   (add-to-list 'package-archives
               '("melpa-stable" . "http://stable.melpa.org/packages/") t)
   (setq package-user-dir (concat user-emacs-directory "elpa"))
   (package-initialize)
   ```
   
   this basically says that
   - we want to use the emacs package system
   - we want to use the melpa-stable repo for packages (see above: no snapshot versions)
   - we want the use the directory named `elpa` under user-emacs-directory (resolves to `~/.emacs.d` here) to store the packages. (I guess to name this directory elpa makes sense as elpa stands for emacs lisp package archive but if this causes confusion we could rename this directory to packages or whatever)

the above code snippet actually helps the maintainer when the time comes to upgrade packages (there are new releases) with a simple `M-x install package RET cider` for example. it also gives a hint to the user I suppose

for a more detailed explanation of emacs [package management](http://ergoemacs.org/emacs/emacs_package_system.html)

hope that answers the above questions. also shall we rename elpa directory then for clarity?

**Comment by ghost** [comment]
Awesome, thanks. I did not realize "elpa" referred both to a general emacs feature as well as a particular package manager. I'd say that renaming the directory makes sense, and you make a good case for having the packages included in the repo. Perhaps a "packages" dir as you suggest might clarify matters. Although, one could almost just copy/paste most of what you just wrote as a comment inside init.el to mitigate any confusion.

**Comment by benedekfazekas** [comment]
rename of directory: done. added bit of explanation of emacs package system to readme.

**Comment by ghost** [comment]
Thanks for everything you guys are doing on this, I'm so happy to see this coming together. When I get done with my work duties today, I'm going to install and play around with all of this. Excited to see refactoring at work. Real curious about yasnippet too, I'm guessing it will be similar to the Live Template feature in Cursive which is cool.

**Comment by benedekfazekas** [comment]
:+1: :)

**Comment by ghost** [comment]
Can you confirm that this would be a good way for a user to have easy access to pulling latest commits from this repo while also having some additional custom configs, all while still having access to run this without any customizations if desired:

1) Clone this repo to local .emacs.d
2) Create new git branch for custom additions
3) Do customizations and commit them to the custom branch. Usually would involve installing additional packages from Melpa, maybe adding a few extra lines at the bottom of init.el or loading an additional my-init.el at the bottom of init.el that contains various things.
4) To get latest version of this repo merged into your local custom repo:
- Checkout local master branch (the branch without your configs)
- Pull changes from github. Your master is now up to date with this clojure-emacs example, matching it exactly, without any of your customizations.
- Switch back to your custom branch
- do a git merge master to merge the latest master into your custom branch you previously setup.

**Comment by expez** [comment]
Would be much easier to just have the user config in a separate file which is loaded last.  That way all the user-specific stuff takes precedence and you won't have to deal with merge conflicts.

**Comment by ghost** [comment]
You mean this repo itself would load a user.el at the bottom of init.el, the end user could then customize it however, and pulls would never touch that user.el since it would remain empty in this repo, right?

I assume the same is true with the elpa/ dir. The user installs new packages that go into elpa/ (as i see it was renamed back in a recent pull request, from the most recent "packages" dir), and pull requests would not conflict since this repo's packages are in site-lisp not elpa. Do I follow you?

**Comment by expez** [comment]
I think if we include an empty `user-config-file` in this project the user would have to stash and pop the changes on each pull.  I'd rather do something like this:

``` elisp
(when (file-exists-p user-config-file)
  (load-file user-config-file))
```

> Do I follow you?

:+1:

**Comment by ghost** [comment]
That's nice, I like it.

**Comment by ghost** [comment]
I noticed that ac-cider is not explicitly noted on the Readme. Is it automatically included in Cider or does it compete with Company, or do I have no idea what I'm talking about? What is the primary auto-complete mechanism used in Clojure with Emacs?

**Comment by benedekfazekas** [comment]
see [here](https://github.com/clojure-emacs/cider#auto-completion)

**Comment by ghost** [comment]
Which feature in this package is responsible for adding the background color to all syntax within the form that contains the current cursor point? I like it, but the color is a bit intense for me (too dark) and am curious where this would be customized. Or maybe the color is set by the theme? If so, any idea what it's called?

**Comment by expez** [comment]
that's probably `hl-sexp`

`M-x customize-face <RET> hl-sexp-face <RET>`

**Comment by ghost** [comment]
that was it, thanks!

**Comment by ghost** [comment]
Is it possible to get pop-up docstrings with autocompletion? Whether they appear in the mini-buffer along with the arity hints or instead appear with the pop-up window near cursor point, doesn't matter, but it is a rather useful tool. How would one configure that?

**Comment by expez** [comment]
This currently doesn't exist for [company-mode](https://github.com/company-mode/company-mode) and is what I personally miss most after moving away from (the imo otherwise inferior) [auto-complete](https://github.com/auto-complete/auto-complete).

I tried writing my own, with some help from the author of company-mode, after opening a feature request [here](https://github.com/company-mode/company-mode/issues/138).  On the windows machine at work, where I sometimes have some time to fiddle with this, it seems to work as I'd like now, but on the linux machine at home it doesn't respect the colors and just uses a black background with white text.

For now you can hit `C-h` or `F1` on a completion candidate to get company-mode to popup a temporary help buffer.

**Comment by ghost** [comment]
I noticed Yasnippet is included in the site-lisp dir here but I can't figure out if it is enabled. I'm trying to use it with David Nolen's snippets but haven't no luck. Is it in fact turned on in this config?

**Comment by benedekfazekas** [comment]
yasnippet is pulled in by `clj-refactor`. You still can use it I think but no cfg- file was created. I suppose using custom clojure templates is out of the scope of this project -- might totally make sense for your localised config project of course

**Comment by ghost** [comment]
ok, i see Yas in the mode line for clojure files so it is clearly on, out of the box. dnolen's snippets page claims it is easy to load them up, and my Messages buffer indicates they were loaded, but they are not available anywhere in an actual source file. I guess I'll direct an issue to the yasnippet repo.

**Comment by MalloZup** [comment]
autogenerated with https://github.com/MalloZup/doghub:  issue inactive since 450 days. Please update the issue or close it
